------------------------
-------- Source --------
------------------------

-- Employee Source Table
CREATE TABLE src_employee (
    employee_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name       NVARCHAR2(100) NOT NULL,
    employee_email      NVARCHAR2(150) NOT NULL UNIQUE,
    department          NVARCHAR2(150) NOT NULL,
    experience_level    NVARCHAR2(50) NOT NULL,
    employee_location   NVARCHAR2(150) NOT NULL,
    manager_id          NUMBER, -- FK to employee_id
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Timesheet Source Table
CREATE TABLE src_timesheet (
    entry_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         NUMBER NOT NULL,
    project_id          NUMBER NOT NULL,
    entry_date          DATE NOT NULL,
    hours_worked        NUMBER(5,2) CHECK (hours_worked >= 0 AND hours_worked <= 24) NOT NULL,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Projects Source Table
CREATE TABLE src_projects (
    project_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name        NVARCHAR2(200) NOT NULL,
    project_code        NVARCHAR2(200) NOT NULL,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Absences Source Table
CREATE TABLE src_absences (
    absence_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         NUMBER NOT NULL,
    absence_type        NVARCHAR2(255) NOT NULL,
    start_date          TIMESTAMP NOT NULL,
    end_date            TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


-------------------------
-------- Staging --------
-------------------------

-- Employee Staging Table
CREATE TABLE stg_employee (
    s_employee_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         NUMBER NOT NULL,
    employee_name       NVARCHAR2(100) NOT NULL,
    employee_email      NVARCHAR2(150) NOT NULL,
    department          NVARCHAR2(150) NOT NULL,
    experience_level    NVARCHAR2(50) NOT NULL,
    employee_location   NVARCHAR2(150) NOT NULL,
    manager_id          NUMBER,
    updated_at          TIMESTAMP NOT NULL,
    load_ts             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    processed_ts        TIMESTAMP,
    process_status      NVARCHAR2(50)
);

-- Timesheet Staging Table
CREATE TABLE stg_timesheet (
    s_entry_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id            NUMBER NOT NULL,
    employee_id         NUMBER NOT NULL,
    project_id          NUMBER NOT NULL,
    entry_date          DATE NOT NULL,
    hours_worked        NUMBER(5,2) NOT NULL,
    updated_at          TIMESTAMP NOT NULL,
    load_ts             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    processed_ts        TIMESTAMP,
    process_status      NVARCHAR2(50)
);

-- Projects Staging Table
CREATE TABLE stg_projects (
    s_project_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          NUMBER NOT NULL,
    project_name        NVARCHAR2(200) NOT NULL,
    project_code        NVARCHAR2(200),
    updated_at          TIMESTAMP NOT NULL,
    load_ts             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    processed_ts        TIMESTAMP,
    process_status      NVARCHAR2(50)
);

-- Absences Staging Table
CREATE TABLE stg_absences (
    s_absence_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    absence_id          NUMBER NOT NULL,
    employee_id         NUMBER NOT NULL,
    absence_type        NVARCHAR2(150) NOT NULL,
    start_date          TIMESTAMP NOT NULL,
    end_date            TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL,
    load_ts             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    processed_ts        TIMESTAMP,
    process_status      NVARCHAR2(50)
);

-- Attendance by Training Staging Table
CREATE TABLE stg_training_attendance (
    s_attendance_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name       NVARCHAR2(100),
    first_join          NVARCHAR2(150),
    last_leave          NVARCHAR2(150),
    email               NVARCHAR2(150),
    training_name       NVARCHAR2(100),
    training_role       NVARCHAR2(100),
    load_ts             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    processed_ts        TIMESTAMP,
    process_status      NVARCHAR2(50)
);

-- Exam Absence Staging Table
CREATE TABLE stg_exam_absence (
    s_ex_absance_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name       NVARCHAR2(100) NOT NULL,
    email               NVARCHAR2(150) NOT NULL,
    week_start_date     DATE,
    monday              NVARCHAR2(150),
    tuesday             NVARCHAR2(150),
    wednesday           NVARCHAR2(150),
    thursday            NVARCHAR2(150),
    friday              NVARCHAR2(150),
    load_ts             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    processed_ts        TIMESTAMP,
    process_status      NVARCHAR2(50)
);

CREATE TABLE etl_metadata (
    table_name          NVARCHAR2(100) PRIMARY KEY,
    last_processed_timestamp TIMESTAMP
);

------------------------
-------- Target --------
------------------------

-- Date Dimension Table
CREATE TABLE tgt_dim_date (
    date_id         NUMBER PRIMARY KEY,
    full_date       DATE NOT NULL,
    day_of_week     NVARCHAR2(20),
    month_num       NUMBER,
    year_num        NUMBER
);

-- Employee Dimension Table (SCD2)
CREATE TABLE tgt_dim_employee (
    employee_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name       NVARCHAR2(100),
    employee_email      NVARCHAR2(150),
    department          NVARCHAR2(150),
    manager_id          NUMBER,
    experience_level    NVARCHAR2(50),
    original_id         NUMBER,
    valid_from          TIMESTAMP,
    valid_to            TIMESTAMP,
    is_current          CHAR(1)
);

-- Project Dimension Table
CREATE TABLE tgt_dim_project (
    project_id      NUMBER PRIMARY KEY,
    project_name    NVARCHAR2(200),
    project_code    NVARCHAR2(200)
);

-- Training Dimension Table
CREATE TABLE tgt_dim_training (
    training_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_name     NVARCHAR2(100),
    instructor        NVARCHAR2(100),
    training_duration NUMBER
);

-- Absence Type Dimension Table
CREATE TABLE tgt_dim_absence_type (
    absence_type_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    absence_type_name   NVARCHAR2(100)
);

-- Fact Employee Activity Table
CREATE TABLE tgt_fact_employee_activity (
    activity_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_id              NUMBER NOT NULL,
    employee_id          NUMBER NOT NULL,
    project_id           NUMBER,
    training_id          NUMBER,
    absence_type_id      NUMBER,
    hours                NUMBER(5,2),
    activity_type        NVARCHAR2(100),
    activity_description NVARCHAR2(255)
);


truncate table src_projects;
TRUNCATE TABLE src_employee;
TRUNCATE TABLE src_timesheet;
TRUNCATE TABLE src_absences;

SELECT count(*) from src_employee;
select count(*) from src_projects;
select count(*) from src_timesheet;
select count(*) from src_absences;
