create table api_request_records (
    id number generated by default as identity primary key,
    api_key varchar2(255),
    endpoint varchar2(255) not null,
    request_method varchar2(10) not null,
    request_input JSON not null,
    request_status varchar2(50) not null,
    request_time timestamp default current_timestamp not null
);

CREATE TABLE service_logs (
    id              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    log_timestamp   TIMESTAMP WITH TIME ZONE NOT NULL,
    log_level       VARCHAR2(10) NOT NULL,
    logger_name     VARCHAR2(128) NOT NULL,
    log_message     CLOB NOT NULL,
    svc_name        VARCHAR2(64) NOT NULL,
    svc_host        VARCHAR2(128)
);

select * from api_request_records;
select * from service_logs;