version: '3.8'

services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.6.0'
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: 'confluentinc/cp-kafka:7.6.0'
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  math-api:
    build: 
      context: .
      dockerfile: math-api/Dockerfile
    container_name: math-api
    env_file:
      - ./math-api/.env.container
    environment: 
      - RUN_ENV=docker
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  log-consumer:
    build: 
      context: .
      dockerfile: logger-microservice/Dockerfile
    container_name: log-consumer
    env_file:
      - ./logger-microservice/.env.container
    environment: 
      - RUN_ENV=docker
    ports:
      - "8001:8001"
    depends_on:
      - kafka
